language: rust
rust:
  - 1.31.0
install:
  - rustup toolchain install nightly-2018-12-06
  - rustup component add rustfmt-preview --toolchain nightly-2018-12-06
before_script:
  - cargo fetch --verbose
script:
  - cargo +nightly-2018-12-06 fmt -- --check && RUST_BACKTRACE=1 cargo test --verbose --all
matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: linux
      sudo: required
    - os: osx
cache: cargo
git:
  depth: 1
